apiVersion: v1
kind: Service
metadata:
  name: golden-path-service
  labels:
    app.kubernetes.io/name: golden-path-service
    app.kubernetes.io/part-of: vaipex-golden-path
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: golden-path-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
