apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: golden-path
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/vaipexlabs/golden-path-service
    newName: golden-path-service
    newTag: local
