commonLabels:
  monitoring.vaipex.io/enabled: "true"

defaultRules:
  create: false

alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: false
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

prometheus:
  prometheusSpec:
    retention: 6h
    scrapeInterval: 15s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector:
      matchLabels:
        monitoring.vaipex.io/enabled: "true"
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector:
      matchLabels:
        monitoring.vaipex.io/enabled: "true"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
