apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: golden-path-service
  namespace: golden-path
  labels:
    monitoring.vaipex.io/enabled: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: golden-path-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
